steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v5.6.0:
        run: tests

  - wait

  - label: ":docker: :rocket: Latest"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-plugin-tester-deploy
      - aws-ssm#v1.0.0:
          parameters:
            BUILDKITE_PLUGIN_DOCKER_LOGIN_USERNAME: /pipelines/buildkite/plugin-tester-deploy/docker-login-username
            DOCKER_LOGIN_PASSWORD: /pipelines/buildkite/plugin-tester-deploy/docker-login-password
      - docker-login#v3.0.0: ~
      - docker-compose#v5.6.0:
          build: latest
          push: latest
    if: |
      build.branch == 'main'

  - label: ":docker: :rocket: Tag"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-plugin-tester-deploy
      - aws-ssm#v1.0.0:
          parameters:
            BUILDKITE_PLUGIN_DOCKER_LOGIN_USERNAME: /pipelines/buildkite/plugin-tester-deploy/docker-login-username
            DOCKER_LOGIN_PASSWORD: /pipelines/buildkite/plugin-tester-deploy/docker-login-password
      - docker-login#v3.0.0: ~
      - docker-compose#v5.6.0:
          build: tag
          push: tag
    if: |
      build.tag != null
