steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v4.13.0:
        run: tests

  - wait

  - label: ":docker: :rocket: Latest"
    plugins:
      docker-login#v2.1.0: ~
      docker-compose#v4.13.0:
        push: latest
    if: |
      build.branch == 'main'

  - label: ":docker: :rocket: Tag"
    plugins:
      docker-login#v2.1.0: ~
      docker-compose#v4.13.0:
        push: tag
    if: |
      build.tag != null
