steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v5.2.0:
        run: tests

  - wait

  - label: ":docker: :rocket: Latest"
    plugins:
      docker-login#v3.0.0: ~
      docker-compose#v5.2.0:
        build: latest
        push: latest
    if: |
      build.branch == 'main'

  - label: ":docker: :rocket: Tag"
    plugins:
      docker-login#v3.0.0: ~
      docker-compose#v5.2.0:
        build: tag
        push: tag
    if: |
      build.tag != null
